services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: group37
    ports:
      - "5432:5432"
    networks:
      - my_app_network
    # Дополнительно: задайте volumes для сохранения данных
    volumes:
      - postgres-data:/var/lib/postgresql/data

  my_spring_app:
    # Убедитесь, что образ существует локально или в реестре
    image: postgres:latest
    container_name: shop
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_db
    depends_on:
      - postgres_db  # Ждёт запуска БД
    networks:
      - my_app_network
    # Дополнительно: проброс портов для приложения


networks:
  my_app_network:
    driver: bridge

volumes:
  postgres-data:  # Для сохранения данных PostgreSQL